version: "3.9"

services:
  leto:
    build:
      context: .
    hostname: leto-dev
    extra_hosts:
      - olympus-dev.local:host-gateway
      - signoz:host-gateway
    devices:
      - /dev/dri/card0
    ipc: host
    volumes:
      - ./frames:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/fort-user/.Xauthority
    command:
      - --dev
      - -vv
    environment:
      - DISPLAY
      - LETO_OTEL_ENDPOINT=signoz:4317
    ports:
      - "4000:4000" # gRPC
      - "4001:4001" # trackers, if using master slave.
      - "4002:4002" # Broadcast
